spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://106.52.194.12:3306/usercenter?useSSL=false'
    username: root
    password: qaz123
  # session 失效时间
  session:
    timeout: 86400

server:
  address: 0.0.0.0
  servlet:
    #指定接口全局
    context-path: /api
    session:
      cookie:
        domain: javat.top   #设置 cookie 的作用域
        secure: false
        same-site: lax
